import { customFetch, type ApiError } from "@workspace/api-client-react";

/**
 * Hand-written helpers for the two speed-focused endpoints added alongside
 * the generated API client:
 *   - POST /api/video/preview          → instant title/thumbnail (oEmbed)
 *   - GET  /api/video/download/direct  → streamed download (no server disk hop)
 *
 * Kept out of packages/api-client/src/generated/** on purpose — that file is
 * regenerated by `orval` from openapi.yaml and hand edits there get
 * silently discarded. Once these endpoints stabilize, add them to
 * openapi.yaml and regenerate instead of maintaining this file long-term.
 */

export interface VideoPreview {
  id: string | null;
  title: string;
  uploader: string;
  thumbnail: string;
}

export type { ApiError };

export function getVideoPreview(url: string, options?: RequestInit): Promise<VideoPreview> {
  return customFetch<VideoPreview>("/api/video/preview", {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify({ url }),
  });
}

// Mirrors the eligibility check on the backend (see isStreamEligible in
// backend/src/routes/video.ts) — kept in sync manually since this is a
// small, stable rule: only synthetic "mp3-*" conversion formats need
// server-side ffmpeg extraction and can't be piped straight through.
export function isDirectDownloadEligible(formatId: string): boolean {
  return !formatId.startsWith("mp3-");
}

const API_BASE = ((import.meta.env.VITE_API_URL as string | undefined) || "").replace(/\/+$/, "");

/**
 * Builds the absolute URL for the direct-streaming download endpoint.
 * Meant to be used as a plain `<a href>` / `window.location` navigation
 * target (NOT fetched via JS) — that way the browser's own network stack
 * streams the response straight to disk with native download-progress UI,
 * instead of buffering the whole file in page memory.
 */
export function getDirectDownloadUrl(videoUrl: string, formatId: string): string {
  const params = new URLSearchParams({ url: videoUrl, formatId });
  return `${API_BASE}/api/video/download/direct?${params.toString()}`;
}
